name: Compile and run unit tests

on:
  push:
    branches:
      - 'beta.*'
      - 'canary'
      - 'develop'
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.18.0
      - run: |
          corepack enable
          corepack prepare pnpm@10.28.2 --activate
      - name: Electronegativity
        uses: doyensec/electronegativity-action@0a76b0251ac45f08eaaf49fdc26c75d1951f82b6 # v2.0
      - name: Upload sarif
        if: github.event_name == 'push'
        uses: github/codeql-action/upload-sarif@b8d3b6e8af63cde30bdc382c0bc28114f4346c88 # v2
        with:
          sarif_file: ../electronegativity_results
      - run: |
          sudo apt update -y
          sudo apt install -y libudev-dev
      - run: pnpm run setup:ci
      - run: pnpm run compile
      - run: pnpm run test:unit
